# 第二十一章：从异常到值

> 在第十九章中，我们讨论了 Kotlin 的错误处理策略，以及如何从 Java 中的异常重构为更功能化的技术。事实上，大多数代码都忽略了错误，希望它们不会发生。我们能做得更好吗？

新加入市场营销团队的人员开始调整我们在第二十章中最后看到的电子表格，这个表格用于生成高价值客户评分。我们不清楚他们具体在做什么，但他们不断导出破坏我们解析的文件，然后要求我们解释堆栈跟踪是什么。这在关系的两端都有些尴尬，所以情况开始变得尴尬。还能有更多的激励吗？

嗯，是的，可能会有。我们还被要求编写一个无人参与的作业，以便市场可以将文件保存到服务器上，而*我们*将自动编写摘要版本。没有人在其中来解释那些堆栈跟踪，似乎我们必须找到一种适当报告错误的方法。

# 确定可能出现问题的内容

这是我们离开时的代码：

```java
fun Sequence<String>.toHighValueCustomerReport(): Sequence<String> {
    val valuableCustomers = this
        .withoutHeader()
        .map(String::toCustomerData)
        .filter { it.score >= 10 }
        .sortedBy(CustomerData::score)
        .toList()
    return sequenceOf("ID\tName\tSpend") +
        valuableCustomers.map(CustomerData::outputLine) +
        valuableCustomers.summarised()
}

private fun List<CustomerData>.summarised(): String =
    sumByDouble { it.spend }.let { total ->
        "\tTOTAL\t${total.toMoneyString()}"
    }

private fun Sequence<String>.withoutHeader() = drop(1)

internal fun String.toCustomerData(): CustomerData =
    split("\t").let { parts ->
        CustomerData(
            id = parts[0],
            givenName = parts[1],
            familyName = parts[2],
            score = parts[3].toInt(),
            spend = if (parts.size == 4) 0.0 else parts[4].toDouble()
        )
    }

private val CustomerData.outputLine: String
    get() = "$id\t$marketingName\t${spend.toMoneyString()}"

private fun Double.toMoneyString() = this.formattedAs("%#.2f")

private fun Any?.formattedAs(format: String) = String.format(format, this)

private val CustomerData.marketingName: String
    get() = "${familyName.toUpperCase()}, $givenName"
```

[示例 21.1 [exceptions-to-values.0:src/main/java/travelator/marketing/HighValueCustomersReport.kt]](https://java-to-kotlin.dev/code.html?ref=21.1&show=file) [(diff)](https://java-to-kotlin.dev/code.html?ref=21.1&show=diff)

如果我们要做好错误处理的彻底工作，首先要做的是确定可能出现的问题。正如我们在第十九章中所看到的，在 Kotlin 中，我们没有检查异常来提供线索，但是在大多数 Java 代码中，它们的使用非常糟糕，因此在这方面两种语言之间没有太大的区别。除非代码已经编写好来传达它可能失败的方式，否则我们将不得不依靠检查、直觉和经验来解决问题。在这种情况下，经验告诉我们，我们实际遇到的失败是由于缺少字段，因此我们可以集中精力解决这个问题，但我们仍然应该对代码的所有方面进行尽职调查。让我们从清单底部的函数开始逐步分析，寻找潜在的错误。

`CustomerData.marketingName`看起来是无害的：

```java
private val CustomerData.marketingName: String
    get() = "${familyName.toUpperCase()}, $givenName"
```

[示例 21.2 [exceptions-to-values.0:src/main/java/travelator/marketing/HighValueCustomersReport.kt]](https://java-to-kotlin.dev/code.html?ref=21.2&show=file) [(diff)](https://java-to-kotlin.dev/code.html?ref=21.2&show=diff)

如果`CustomerData`是用 Java 实现的，我们可能会发现`familyName`解析为`null`，因此在尝试`toUpperCase()`时会抛出异常，但在 Kotlin 中不会这样，所以也不会发生。与所有代码一样，该函数可能会抛出`Error`的子类（如`OutOfMemoryError`），但通常是安全的。从现在开始，我们将不将抛出`Error`视为普通情况，因此不在我们的分析之内。

现在是`formattedAs`：

```java
private fun Any?.formattedAs(format: String) = String.format(format, this)
```

[示例 21.3 [exceptions-to-values.0:src/main/java/travelator/marketing/HighValueCustomersReport.kt]](https://java-to-kotlin.dev/code.html?ref=21.3&show=file) [(diff)](https://java-to-kotlin.dev/code.html?ref=21.3&show=diff)

`String.format(format, this)` 实现为 `java.lang.String::format`，如果 `format` 与其它输入不兼容，文档中说明会抛出 `IllegalFormatException`。这是一个[偏函数](https://oreil.ly/ErpGo)：只针对某些参数值返回结果。在这种情况下，它可以为所有 `Double` 的值返回结果，但只有在我们使用非常特定的 `format` 值时才能。幸运的是，我们只是传递了一个特定的 `format`，即值 `%#.2f`，我们知道它是有效的，所以这个函数及其唯一的调用者 `Double.toMoneyString()` 不应该失败。如果它们失败了，那是因为我们的分析有误（或其假设已不再成立），运行时错误是一种合理的方式来表明程序员的错误。

接下来我们有：

```java
private val CustomerData.outputLine: String
    get() = "$id\t$marketingName\t${spend.toMoneyString()}"
```

[示例 21.4 [exceptions-to-values.0:src/main/java/travelator/marketing/HighValueCustomersReport.kt]](https://java-to-kotlin.dev/code.html?ref=21.4&show=file) [(diff)](https://java-to-kotlin.dev/code.html?ref=21.4&show=diff)

这只调用我们刚刚推断不应该失败的代码，因此按失败的传递性原则，它也应该是安全的。

注意，到目前为止都很简单，因为这些函数都是计算函数（“Calculations”）。它们不依赖于任何外部状态，所以我们可以通过查看它们来推理。

到目前为止一切顺利，现在是 `String.toCustomerData()`：

```java
internal fun String.toCustomerData(): CustomerData =
    split("\t").let { parts ->
        CustomerData(
            id = parts[0],
            givenName = parts[1],
            familyName = parts[2],
            score = parts[3].toInt(),
            spend = if (parts.size == 4) 0.0 else parts[4].toDouble()
        )
    }
```

[示例 21.5 [exceptions-to-values.0:src/main/java/travelator/marketing/HighValueCustomersReport.kt]](https://java-to-kotlin.dev/code.html?ref=21.5&show=file) [(diff)](https://java-to-kotlin.dev/code.html?ref=21.5&show=diff)

好吧，这又是一个偏函数：几乎没有 `String` 接收者的值会导致该函数能够返回结果。幸运的是，实践中我们获取的几乎所有值都是可以接受的，这就是为什么错误处理现在才成为优先事项的原因。但是，可能出现什么问题呢？

从函数顶部开始，如果我们传递空分隔符给`String.split`，它可能会表现得很奇怪，但我们并没有。接着，可能会出现部分不足的情况，这样`parts[n]`会抛出`IndexOutOfBoundsException`。最后，`parts[3]`可能不表示一个`Int`，或者`parts[4]`可能不表示一个`Double`，这两种情况都会抛出`NumberFormatException`。

已经确定 `toCustomerData` 如果传入不符合我们格式规范的 `String` 可能会失败，那我们该怎么办呢？目前，所有可能导致失败的方式都会抛出异常，程序会以不友好的错误消息中止，并且会有市场部门找我们。这引出了两个后续问题：“我们应该中止吗？”以及“如何改进错误消息以便市场部门理解？”

正如我们在 第十九章 中看到的，我们不应该使用异常来中止可预测的错误。 Kotlin 中的未检查异常的缺失（以及在 Java 中的不使用）意味着如果我们这样做，我们失去了表明代码容易失败的机会。然后，我们代码的调用者必须像我们目前正在做的那样：推理出实现中的每一行代码。即使在那之后，实现可能会发生变化，默默地使结果无效。

如果我们不打算抛出异常，那么最便宜的更改（只要我们的调用方都是 Kotlin）就是在失败时返回 `null`。客户端代码将被迫考虑 `null` 情况并相应地采取行动。例如：

```java
internal fun String.toCustomerData(): CustomerData? =
    split("\t").let { parts ->
        if (parts.size < 4)
            null
        else
            CustomerData(
                id = parts[0],
                givenName = parts[1],
                familyName = parts[2],
                score = parts[3].toInt(),
                spend = if (parts.size == 4) 0.0 else parts[4].toDouble()
            )
    }
```

[示   [示例 21.6 [exceptions-to-values.1:src/main/java/travelator/marketing/HighValueCustomersReport.kt]](https://java-to-kotlin.dev/code.html?ref=21.6&show=file) [(diff)](https://java-to-kotlin.dev/code.html?ref=21.6&show=diff)

我们本可以选择简单地将整个实现包装在 `try` 块中，并从 `catch` 中返回 `null`，但在这里，我们比反应更主动。这意味着如果相关字段无法转换为 `Int` 或 `Double`，代码仍将抛出异常。我们会解决这个问题。

这个变化破坏了 `toHighValueCustomerReport`，现在必须考虑失败的可能性：

```java
fun Sequence<String>.toHighValueCustomerReport(): Sequence<String> {
    val valuableCustomers = this
        .withoutHeader()
        .map(String::toCustomerData)
        .filter { it.score >= 10 } ![1](img/1.png)
        .sortedBy(CustomerData::score)
        .toList()
    return sequenceOf("ID\tName\tSpend") +
        valuableCustomers.map(CustomerData::outputLine) +
        valuableCustomers.summarised()
}
```

[示例 21.7 [exceptions-to-values.1:src/main/java/travelator/marketing/HighValueCustomersReport.kt]](https://java-to-kotlin.dev/code.html?ref=21.7&show=file) [(diff)](https://java-to-kotlin.dev/code.html?ref=21.7&show=diff)

![1](img/#co_introduction_CO47-1)

因为 `it` 是可空的，所以无法编译。

现在，如果我们只想忽略格式错误的输入行，我们可以使用 `filterNotNull` 让一切重新运行：

```java
fun Sequence<String>.toHighValueCustomerReport(): Sequence<String> {
    val valuableCustomers = this
        .withoutHeader()
        .map(String::toCustomerData)
        .filterNotNull()
        .filter { it.score >= 10 }
        .sortedBy(CustomerData::score)
        .toList()
    return sequenceOf("ID\tName\tSpend") +
        valuableCustomers.map(CustomerData::outputLine) +
        valuableCustomers.summarised()
}
```

[示例 21.8 [exceptions-to-values.2:src/main/java/travelator/marketing/HighValueCustomersReport.kt]](https://java-to-kotlin.dev/code.html?ref=21.8&show=file) [(diff)](https://java-to-kotlin.dev/code.html?ref=21.8&show=diff)

我们没有任何测试来支持这一点，而且我们真的应该写一些测试，但是现在我们将继续进行，因为这是一种探索性的尝试性解决方案。从这里开始，我们可以使用 `null` 来表示我们知道 `toCustomerData` 可以失败的其他方式：

```java
internal fun String.toCustomerData(): CustomerData? =
    split("\t").let { parts ->
        if (parts.size < 4)
            return null
        val score = parts[3].toIntOrNull() ?:
            return null
        val spend = if (parts.size == 4) 0.0 else parts[4].toDoubleOrNull() ?:
            return null
        CustomerData(
            id = parts[0],
            givenName = parts[1],
            familyName = parts[2],
            score = score,
            spend = spend
        )
    }
```

[示例 21.9 [exceptions-to-values.3:src/main/java/travelator/marketing/HighValueCustomersReport.kt]](https://java-to-kotlin.dev/code.html?ref=21.9&show=file) [(diff)](https://java-to-kotlin.dev/code.html?ref=21.9&show=diff)

注意，Kotlin 标准库通过提供 `String::toSomethingOrNull` 函数来帮助我们处理此错误处理约定。现在，由回到 `toHighValueCustomer​Re⁠port` 并想想如何处理它们，而不是假装它们没有发生（读作 `filterNotNull`）。

我们可以在第一个错误上中止，但值得额外努力收集所有的问题行并以某种方式报告它们。*某种方式*有点模糊，但有趣的是它有一个类型：在这种情况下是`(String) -> Unit`。也就是说，我们可以将该做什么委托给一个接受错误行并且不影响结果的函数。我们在“异常之前的错误处理”中提到了这种技术。为了说明这一点，让我们添加一个测试：

```java
@Test
fun `calls back on parsing error`() {
    val lines = listOf(
        "ID\tFirstName\tLastName\tScore\tSpend",
        "INVALID LINE",
        "1\tFred\tFlintstone\t11\t1000.00",
    )

    val errorCollector = mutableListOf<String>()
    val result = lines
        .asSequence()
        .constrainOnce()
        .toHighValueCustomerReport { badLine -> ![1](img/1.png)
            errorCollector += badLine
        }
        .toList()

    assertEquals(
        listOf(
            "ID\tName\tSpend",
            "1\tFLINTSTONE, Fred\t1000.00",
            "\tTOTAL\t1000.00"
        ),
        result
    )
    assertEquals(
        listOf("INVALID LINE"),
        errorCollector
    )
}
```

[示例 21.10 [exceptions-to-values.4:src/test/java/travelator/marketing/HighValueCustomersReportTests.kt]](https://java-to-kotlin.dev/code.html?ref=21.10&show=file) [(diff)](https://java-to-kotlin.dev/code.html?ref=21.10&show=diff)

![1](img/#co_introduction_CO48-1)

这个 lambda 在下一个示例中实现了`onErrorLine`。

让我们用可能能够正常工作的最简单的方法来实现它：

```java
fun Sequence<String>.toHighValueCustomerReport(
    onErrorLine: (String) -> Unit = {}
): Sequence<String> {
    val valuableCustomers = this
        .withoutHeader()
        .map { line ->
            val customerData = line.toCustomerData()
            if (customerData == null)
                onErrorLine(line)
            customerData
        }
        .filterNotNull()
        .filter { it.score >= 10 }
        .sortedBy(CustomerData::score)
        .toList()
    return sequenceOf("ID\tName\tSpend") +
        valuableCustomers.map(CustomerData::outputLine) +
        valuableCustomers.summarised()
}
```

[示例 21.11 [exceptions-to-values.4:src/main/java/travelator/marketing/HighValueCustomersReport.kt]](https://java-to-kotlin.dev/code.html?ref=21.11&show=file) [(diff)](https://java-to-kotlin.dev/code.html?ref=21.11&show=diff)

这仍然在过滤出错误行，但只有在将它们传递给`onErrorLine`后才会这样做，它可以决定要执行什么操作。在`main`中，我们将使用它将错误打印到`System.err`，然后中止：

```java
fun main() {
    System.`in`.reader().use { reader ->
        System.out.writer().use { writer ->
            val errorLines = mutableListOf<String>()
            val reportLines = reader
                .asLineSequence()
                .toHighValueCustomerReport {
                    errorLines += it
                }
            if (errorLines.isNotEmpty()) {
                System.err.writer().use { error ->
                    error.appendLine("Lines with errors")
                    errorLines.asSequence().writeTo(error)
                }
                exitProcess(-1)
            } else {
                reportLines.writeTo(writer)
            }
        }
    }
}
```

[示例 21.12 [exceptions-to-values.4:src/main/java/travelator/marketing/HighValueCustomersMain.kt]](https://java-to-kotlin.dev/code.html?ref=21.12&show=file) [(diff)](https://java-to-kotlin.dev/code.html?ref=21.12&show=diff)

这是本书中我们仅有的几处借助可变`List`的地方之一。为什么在这里？例如，我们可以将`toHighValueCustomerReport`更改为返回`Pair<Sequence<String>, List<String>>`，其中第二个元素是错误。这种方案的主要优点是它允许调用者通过在`onErrorLine`中抛出异常来尽早中止。为了最大灵活性，我们甚至可以有一个具有签名`(String) -> CustomerData?`的错误处理策略，以便调用者可以提供替代方法，从而允许从任何特定行的错误中恢复。

在第二十章中，我们费了一番功夫将`toHighValueCustomerReport`从一个操作转换为一个计算。然后，我们通过从`Sequence`读取和写入来放松了纯度，但在这里，我们引入了一个返回`Unit`的错误处理函数，这是我们引入了一个操作的明确迹象。只要该操作的范围限定在错误处理中，并且任何副作用都像在这个`main`中一样，限制在局部变量中，这是另一个合理的折衷方案。这是一种灵活且表达清晰的应急错误处理解决方案，但并非纯粹。

# 表示错误

现在我们正在传达*我们的解析可能失败*（通过返回可空类型），以及*它在哪里失败*（通过回调传递行），我们是否可以更好地传达*为什么*它失败了？

返回结果类型而不是可空类型允许我们指定存在哪些失败模式并在发生时提供详细信息。让我们将`String.to​Custo⁠merData()`更改为返回`Result`而不是可空：

```java
internal fun String.toCustomerData(): Result<CustomerData, ParseFailure> =
    split("\t").let { parts ->
        if (parts.size < 4)
            return Failure(NotEnoughFieldsFailure(this))
        val score = parts[3].toIntOrNull() ?:
            return Failure(ScoreIsNotAnIntFailure(this))
        val spend = if (parts.size == 4) 0.0 else parts[4].toDoubleOrNull() ?:
            return Failure(SpendIsNotADoubleFailure(this))
        Success(
            CustomerData(
                id = parts[0],
                givenName = parts[1],
                familyName = parts[2],
                score = score,
                spend = spend
            )
        )
    }
```

[示例 21.13 [exceptions-to-values.5:src/main/java/travelator/marketing/HighValueCustomersReport.kt]](https://java-to-kotlin.dev/code.html?ref=21.13&show=file) [(diff)](https://java-to-kotlin.dev/code.html?ref=21.13&show=diff)

正如我们在第十九章中所做的那样，我们创建一个密封类来表示解析失败的原因：

```java
sealed class ParseFailure(open val line: String)
data class NotEnoughFieldsFailure(override val line: String) :
    ParseFailure(line)
data class ScoreIsNotAnIntFailure(override val line: String) :
    ParseFailure(line)
data class SpendIsNotADoubleFailure(override val line: String) :
    ParseFailure(line)
```

[示例 21.14 [exceptions-to-values.5:src/main/java/travelator/marketing/HighValueCustomersReport.kt]](https://java-to-kotlin.dev/code.html?ref=21.14&show=file) [(diff)](https://java-to-kotlin.dev/code.html?ref=21.14&show=diff)

说实话，在这种情况下（一个单一的数据类携带失败的行和一个字符串原因就足够了），这有些过度，但我们正在举例展示错误工程的卓越性。我们可以通过调用`toCustomerData`的调用者并在`ParseFailure`中保持的数据上调用`onErrorLine`，然后在出现`Error`时产生`null`来修复`toCustomerData`的调用者。这样可以通过当前的测试：

```java
fun Sequence<String>.toHighValueCustomerReport(
    onErrorLine: (String) -> Unit = {}
): Sequence<String> {
    val valuableCustomers = this
        .withoutHeader()
        .map { line ->
            line.toCustomerData().recover {
                onErrorLine(line)
                null
            }
        }
        .filterNotNull()
        .filter { it.score >= 10 }
        .sortedBy(CustomerData::score)
        .toList()
    return sequenceOf("ID\tName\tSpend") +
        valuableCustomers.map(CustomerData::outputLine) +
        valuableCustomers.summarised()
}
```

[示例 21.15 [exceptions-to-values.5:src/main/java/travelator/marketing/HighValueCustomersReport.kt]](https://java-to-kotlin.dev/code.html?ref=21.15&show=file) [(diff)](https://java-to-kotlin.dev/code.html?ref=21.15&show=diff)

然而，我们真正想要的是暴露`ParseFailure`。让我们首先更改测试以收集`ParseFailure`而不是带有错误行的行：

```java
val errorCollector = mutableListOf<ParseFailure>()
val result = lines
    .asSequence()
    .constrainOnce()
    .toHighValueCustomerReport { badLine ->
        errorCollector += badLine
    }
    .toList()
assertEquals(
    listOf(NotEnoughFieldsFailure("INVALID LINE")),
    errorCollector
)
```

[示例 21.16 [exceptions-to-values.6:src/test/java/travelator/marketing/HighValueCustomersReportTests.kt]](https://java-to-kotlin.dev/code.html?ref=21.16&show=file) [(diff)](https://java-to-kotlin.dev/code.html?ref=21.16&show=diff)

现在我们可以更改`onErrorLine`以接受失败：

```java
fun Sequence<String>.toHighValueCustomerReport(
    onErrorLine: (ParseFailure) -> Unit = {}
): Sequence<String> {
    val valuableCustomers = this
        .withoutHeader()
        .map { line ->
            line.toCustomerData().recover {
                onErrorLine(it)
                null
            }
        }
        .filterNotNull()
        .filter { it.score >= 10 }
        .sortedBy(CustomerData::score)
        .toList()
    return sequenceOf("ID\tName\tSpend") +
        valuableCustomers.map(CustomerData::outputLine) +
        valuableCustomers.summarised()
}
```

[示例 21.17 [exceptions-to-values.6:src/main/java/travelator/marketing/HighValueCustomersReport.kt]](https://java-to-kotlin.dev/code.html?ref=21.17&show=file) [(diff)](https://java-to-kotlin.dev/code.html?ref=21.17&show=diff)

这样`main`就可以报告原因和行：

```java
if (errorLines.isNotEmpty()) {
    System.err.writer().use { error ->
        error.appendLine("Lines with errors")
        errorLines.asSequence().map { parseFailure ->
            "${parseFailure::class.simpleName} in ${parseFailure.line}"
        }.writeTo(error)
    }
    exitProcess(-1)
} else {
    reportLines.writeTo(writer)
}
```

[示例 21.18 [exceptions-to-values.6:src/main/java/travelator/marketing/HighValueCustomersMain.kt]](https://java-to-kotlin.dev/code.html?ref=21.18&show=file) [(diff)](https://java-to-kotlin.dev/code.html?ref=21.18&show=diff)

我们可能没有使用`ParseFailure`的运行时类型来处理不同的错误，但我们已经在错误消息中使用了其名称，因此至少我们从我们的小密封类层次结构中获得了一些价值。如果生成的错误消息不足以让营销部门修复其输入，那么我们可以在密封类上使用`when`表达式来区分不同类型的失败，就像我们在“层次”中看到的那样。

此时，一切都在编译并且我们的测试通过，所以至少在这个小世界中一切都很好。如果我们有更多客户端代码调用此 API，或者我们的更改需要通过更多代码层级传播，我们可能会选择比在一个文件中更改代码并修复错误更复杂的重构策略。然而，通常情况下，当我们能够在最多几分钟内使代码编译并通过测试时，这种努力是不值得的。如果我们发现我们的野心超过了我们的承受能力，那么回退并采取更加考虑周到的方法是很容易的。

现在测试通过了，我们应该回头确保一切都尽可能整洁和表达力强。特别是，在`toHighValueCustomerReport`中，我们做的是为了让一切重新工作而采取的最快的方法：

```java
fun Sequence<String>.toHighValueCustomerReport(
    onErrorLine: (ParseFailure) -> Unit = {}
): Sequence<String> {
    val valuableCustomers = this
        .withoutHeader()
        .map { line ->
            line.toCustomerData().recover {
                onErrorLine(it)
                null
            }
        }
        .filterNotNull()
        .filter { it.score >= 10 }
        .sortedBy(CustomerData::score)
        .toList()
    return sequenceOf("ID\tName\tSpend") +
        valuableCustomers.map(CustomerData::outputLine) +
        valuableCustomers.summarised()
}
```

[示例 21.19 [exceptions-to-values.6:src/main/java/travelator/marketing/HighValueCustomersReport.kt]](https://java-to-kotlin.dev/code.html?ref=21.19&show=file) [(差异)](https://java-to-kotlin.dev/code.html?ref=21.19&show=diff)

从`recover`块中产生`null`然后用`filterNotNull`跳过这些东西有点不令人满意。它不能直接传达它的工作方式，并且妨碍了愉快的路径。我们希望能找到一个更好的`valuableCustomers`表达式的表达方式，但事实上，在你们的作者看来，其他一切都有点更糟。如果您找到一个简单而好的方法，请告诉我们。

类似地，`toCustomerData`中的提前返回看起来有点丑陋：

```java
internal fun String.toCustomerData(): Result<CustomerData, ParseFailure> =
    split("\t").let { parts ->
        if (parts.size < 4)
            return Failure(NotEnoughFieldsFailure(this))
        val score = parts[3].toIntOrNull() ?:
            return Failure(ScoreIsNotAnIntFailure(this))
        val spend = if (parts.size == 4) 0.0 else parts[4].toDoubleOrNull() ?:
            return Failure(SpendIsNotADoubleFailure(this))
        Success(
            CustomerData(
                id = parts[0],
                givenName = parts[1],
                familyName = parts[2],
                score = score,
                spend = spend
            )
        )
    }
```

[示例 21.20 [exceptions-to-values.6:src/main/java/travelator/marketing/HighValueCustomersReport.kt]](https://java-to-kotlin.dev/code.html?ref=21.20&show=file) [(差异)](https://java-to-kotlin.dev/code.html?ref=21.20&show=diff)

“适当”的功能性错误处理不会提前返回，而是使用`flatMap`链。易于紧张的读者可能希望离开：

```java
internal fun String.toCustomerData(): Result<CustomerData, ParseFailure> =
    split("\t").let { parts ->
        parts
            .takeUnless { it.size < 4 }
            .asResultOr { NotEnoughFieldsFailure(this) }
            .flatMap { parts ->
                parts[3].toIntOrNull()
                    .asResultOr { ScoreIsNotAnIntFailure(this) }
                    .flatMap { score: Int ->
                        (if (parts.size == 4) 0.0
                        else parts[4].toDoubleOrNull())
                            .asResultOr { SpendIsNotADoubleFailure(this) }
                            .flatMap { spend ->
                                Success(
                                    CustomerData(
                                        id = parts[0],
                                        givenName = parts[1],
                                        familyName = parts[2],
                                        score = score,
                                        spend = spend
                                    )
                                )
                            }
                    }
            }
    }
```

[示例 21.21 [exceptions-to-values.7:src/main/java/travelator/marketing/HighValueCustomersReport.kt]](https://java-to-kotlin.dev/code.html?ref=21.21&show=file) [(差异)](https://java-to-kotlin.dev/code.html?ref=21.21&show=diff)

你们的作者甚至比大多数人更喜欢单一表达式，但如果这是`Result`（故意的双关语），那就不行了。在这里，我们显然可以通过引入更多函数来简化（例如，`asResultOr ... flatMap`看起来就像是一个试图获得的概念）。其他一些结果库可以让我们滥用协程或异常来达到与之前提前返回相同的效果，但是没有更好的语言支持来避免每个语句都需要缩进，Kotlin 的语法更青睐于在这些情况下提前返回。虽然我们在本书中没有专门讨论过这一点，但 Lambda 可以被内联编译，因此支持从其包围函数返回的事实鼓励我们在这种情况下使用命令式代码。因此，对我们来说，提前返回是可以接受的。

最后，在我们最后检查之前返回`main`：

```java
fun main() {
    System.`in`.reader().use { reader ->
        System.out.writer().use { writer ->
            val errorLines = mutableListOf<ParseFailure>()
            val reportLines = reader
                .asLineSequence()
                .toHighValueCustomerReport {
                    errorLines += it
                }
            if (errorLines.isNotEmpty()) {
                System.err.writer().use { error ->
                    error.appendLine("Lines with errors")
                    errorLines.asSequence().map { parseFailure ->
                        "${parseFailure::class.simpleName} in ${parseFailure.line}"
                    }.writeTo(error)
                }
                exitProcess(-1)
            } else {
                reportLines.writeTo(writer)
            }
        }
    }
}
```

[例子 21.22 [exceptions-to-values.6:src/main/java/travelator/marketing/HighValueCustomersMain.kt]](https://java-to-kotlin.dev/code.html?ref=21.22&show=file) [(差异)](https://java-to-kotlin.dev/code.html?ref=21.22&show=diff)

这三层嵌套的`use`使实际结构变得模糊，而函数深处的`exitProcess`也有些靠不住。我们可以定义自己的`using`重载来解决前者，并传递一个退出码来解决后者（这是使用数据而不是控制流来处理错误的示例）。我们还可以提取一个扩展函数来打印错误：

```java
fun main() {
    val statusCode = using(
        System.`in`.reader(),
        System.out.writer(),
        System.err.writer()
    ) { reader, writer, error ->
        val errorLines = mutableListOf<ParseFailure>()
        val reportLines = reader
            .asLineSequence()
            .toHighValueCustomerReport {
                errorLines += it
            }
        if (errorLines.isEmpty()) {
            reportLines.writeTo(writer)
            0
        } else {
            errorLines.writeTo(error)
            -1
        }
    }
    exitProcess(statusCode)
}

inline fun <A : Closeable, B : Closeable, C : Closeable, R> using(
    a: A,
    b: B,
    c: C,
    block: (A, B, C) -> R
): R =
    a.use {
        b.use {
            c.use {
                block(a, b, c)
            }
        }
    }

private fun List<ParseFailure>.writeTo(error: OutputStreamWriter) {
    error.appendLine("Lines with errors")
    asSequence().map { parseFailure ->
        "${parseFailure::class.simpleName} in ${parseFailure.line}"
    }.writeTo(error)
}
```

[例子 21.23 [exceptions-to-values.8:src/main/java/travelator/marketing/HighValueCustomersMain.kt]](https://java-to-kotlin.dev/code.html?ref=21.23&show=file) [(差异)](https://java-to-kotlin.dev/code.html?ref=21.23&show=diff)

# I/O 怎么样？

那几乎是足够好的了。然而，在我们离开之前，我们应该考虑一下 I/O 错误。由于我们引入了`List`然后是`Sequence`，我们的报告生成代码不必担心写入失败，因为迭代结果行并实际执行写入是调用代码的责任。在这种情况下的`main`函数合理地假设`System.out`总是存在，但当我们实现激发此重构的无人看管作业时，我们将不得不处理文件或网络套接字即使在我们开始时它们是打开的也可能消失的可能性。

读取时也存在类似的情况。我们现在正在迭代`Sequence`中的每个`String`。在测试代码中，这些都在内存中，但在生产中，它们是从文件（通过`System.in`）中获取的。因此，我们的`Sequence`操作可能会因为报告生成不知情的`IOExceptions`而失败。

在这些情况下，`toHighValueCustomerReport()`很少能或应该做什么。一旦我们开始在这里读取，就没有实际的恢复 I/O 错误的方法——中止整个操作是明智的选择。幸运的是，现在责任完全落在调用者（在这种情况下是`main`）身上。`toHighValueCustomerReport`通过其`onErrorLine`参数信号化它知道的错误（解析失败）及其表示方式（`ParseFailure`的子类）。`IOException`不是它的责任。正是`main`将 I/O 支持的`Sequence`传入`toHighValueCustomerReport`，因此`main`应该意识到`toHighValueCustomerReport`可能因此失败并相应地处理。让我们添加那段代码：

```java
fun main() {
    val statusCode = try {
        using(
            System.`in`.reader(),
            System.out.writer(),
            System.err.writer()
        ) { reader, writer, error ->
            val errorLines = mutableListOf<ParseFailure>()
            val reportLines = reader
                .asLineSequence()
                .toHighValueCustomerReport {
                    errorLines += it
                }
            if (errorLines.isEmpty()) {
                reportLines.writeTo(writer)
                0
            } else {
                errorLines.writeTo(error)
                -1
            }
        }
    } catch (x: IOException) {
        System.err.println("IO error processing report ${x.message}")
        -1
    }
    exitProcess(statusCode)
}
```

[例子 21.24 [exceptions-to-values.9:src/main/java/travelator/marketing/HighValueCustomersMain.kt]](https://java-to-kotlin.dev/code.html?ref=21.24&show=file) [(差异)](https://java-to-kotlin.dev/code.html?ref=21.24&show=diff)

对于这个应用来说可能有点过头了，但它展示了捕获和处理我们*期望*的异常模式（例如为`IOException`打印一个相对友好的消息），但允许其他所有异常泄露并退出应用程序。如果我们遵循第十九章的策略，*意外*的异常要么是不可恢复的环境错误，要么是程序员错误。在这两种情况下，默认的 JVM 行为是在打印堆栈跟踪后退出进程，这样我们有一定的机会诊断问题。当我们将其转换为无人看管的服务器作业时，我们将类似地处理顶层处理程序函数中的预期错误。我们可能会在`IOException`上中止或重新尝试整个交互，如果认为问题可能是暂时性的。我们知道重新尝试对解析错误无济于事，因此我们必须记录这些错误和/或将通知发送到某个地方。处理程序函数中的意外错误通常允许泄漏到通用异常处理代码，该代码将记录它们并在返回线程到其池之前发送内部服务器错误状态。

# 继续前进

在工程中，我们经常不得不做出妥协。特别是，试图简化一件事往往会使另一件事复杂化。I/O 以两种方式使我们的软件复杂化。它是一种行为，因此我们不能简单地忽视它何时发生或重构时发生；它也容易出现错误，如果我们想要一个强大的系统，就必须处理这些错误。这些错误可能是简单的环境故障导致无法读取或写入，或者是因为我们正在读取的内容不符合我们的预期——例如，当营销文件以不良格式结尾时。

行为和错误都会影响调用者，而解决方法在两种情况下是一样的：将代码移近入口点，以减少系统的污染。因此，在这个领域，我们无需做出妥协，却可以一举解决两个问题。通过将 I/O 操作移到系统外部，我们可以减少行为和错误增加代码复杂性的方式。
